receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: <SIG_NOZ_ENDPOINT>:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
